/********************************************
 * Type specific TypeSupport header file.   *
 * Autogenerated by CoreDx DDL compiler.    *
 * Do no edit - edits may be overwritten.   *
 ********************************************/

#ifndef _ROBOBRAWL_TYPESUPPORT_HH
#define _ROBOBRAWL_TYPESUPPORT_HH

#include <dds/dds.hpp>
#include "robobrawl.hh"

#endif

