//aight


enum DeviceRole {
       ROLE_UNKNOWN, // Unknown value. This is a generic placeholder representing the case in which an appropriate value could not be determined.  Never transmitted in this version of the standard.
       ROLE_CONTROL, 
       ROLE_BUTTON_ORANGE,
       ROLE_BUTTON_BLUE,
       ROLE_CLOCK, 
       
   }; // enum DeviceRole


enum Colors{
    COLOR_GREEN,
    COLOR_ORANGE,
    COLOR_BLUE,
    COLOR_YELLOW,
    COLOR_RED,
};


struct Heartbeat{
    string deviceId;
    uint32 sequenceNumber;
};

struct SysName{
    string deviceId;

    string sysName;
};


struct timeValue{
    float seconds;
    long minutes;
};

struct ClockCommand{

    string sysName;

    long isOff;

    long doDisplayTime;

    timeValue time;

    Colors mainColor;

    Colors blueGearColor;

    Colors orangeGearColor;

};

struct ButtonCommand{

    string sysName;

    // need state vals for these
    long orangeState;

    long blueState;

};

struct ButtonData{
    string deviceId;

    string sysName;

    long mainPressed;

    long tapoutPressed;
};





struct DeviceInfo{
    @key string deviceId;

    DeviceRole role;

    string sysName;

    string displayName;


};